Adding the current and wip validator results to the manifest.json
FirelyTeam/fhir-test-cases pull request #1
Opened 2021-04-15 13:59 UTC by marcovisserFurore

2021-04-15 15:57 UTC, mmsmits requested changes

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "warnings" : [
Missing element: "warnings"

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -        "errorCount" : 0
missing element: errorCount

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "errorCount" : 0,
missing element: errorCount

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "x-errors" : [
missing element: x-errors

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -        "errorCount" : 1
missing element: errorCount

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -        "explanatino" : "one about no matcing profiles, then 2 errors for the profiles that con't match",
explanatino.. -> explanation

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "erors" : "missing sub-extension",
erors -> errors 
missing

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "erors" : "unknown sub-extension",
erors -> errors
missing

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "logical" : {
missing logical and child elements

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -        "error-locations" : [
missing error-locations

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -        "assumeValidRestReferences" : true,
missing assumeValidRestReference

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -        "assumeValidRestReferences" : true,
missing assumeValidRestReference

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -        "assumeValidRestReferences" : true,
missing assumeValidRestReference

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -          "debug" : true,
missing debug element

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -        "earningCount" : 1,
missing element earningCount -> warningCount

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -          "background" : "see https://chat.fhir.org/#narrow/stream/179166-implementers/topic/why.20does.20this.20.24validate.20fail.3F/near/197350736 - slicing isn't understood by the validator"
missing element "background"

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "note" : "Same as good1, but with security checks on",
missing element "note"

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "description" : "Testing versioned reference to questionnaire",
missing element: "description"

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -          "comment" : "This needs to be fixed so that it's not just an error",
missing element: "comment"

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -          "debug" : true,
missing element: "debug"

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "generate-shapshot" : true,
missing element: "generate-shapshot"

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "generate-shapshot" : true,
missing element "generate-shapshot"

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "fetcher" : "standalone",
missing element "fetcher"

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "description": "",
missing element "description"

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "fetcher" : "standalone",
missing element "fetcher"

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "description": "",
see above

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "description": "Can't use a code defined in a supplement",
same

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "description": "Supplement can't define new codes",
same

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "description": "Reported Issue validating an answer in a questionnaire",
same

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "description": "Testing primitive extensions",
same

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "description": "ID validation in r2b, and validating unknown code systems against expansions",
same

2021-04-15 15:57 UTC, mmsmits commented on validator/manifest.json
> -      "fetcher" : "standalone",
missing elelemt "fetcher"

2021-04-19 14:12 UTC, ewoutkramer approved these changes

2021-04-19 15:25 UTC, mmsmits approved these changes

2021-04-19 15:25 UTC, merged